version: '3.8'

services:
  mercury_api:
    dns:
        - 8.8.8.8
    build:
      context: ./ # We need run this from the root of the project
      dockerfile: ./docker/planner/develop/fastapi/Dockerfile
    volumes:
      - .:/usr/src/app
      - dependencies:/usr/local/lib/python3.11/site-packages
    ports:
      - 8080:8080
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost:8080/api/healthcheck || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 2s
    depends_on:
      - database

  database:
    image: postgres:15
    volumes:
      - mercury-db:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - 5433:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  mercury-db:
  dependencies:
