name: Test Cases

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
      - develop
      - "releases/**"

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Test Cases
        run: ./init.sh -e test run --rm planner_api /test.sh

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Test Cases
        run: ./init.sh -e test run --rm planner
